[2020-12-28 15:24:52,300] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: test_slack.slack 2020-12-28T07:24:51.014007+00:00 [queued]>
[2020-12-28 15:24:52,311] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: test_slack.slack 2020-12-28T07:24:51.014007+00:00 [queued]>
[2020-12-28 15:24:52,311] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 15:24:52,311] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 15:24:52,311] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 15:24:52,319] {taskinstance.py:1038} INFO - Executing <Task(SlackWebhookOperator): slack> on 2020-12-28T07:24:51.014007+00:00
[2020-12-28 15:24:52,321] {standard_task_runner.py:51} INFO - Started process 27974 to run task
[2020-12-28 15:24:52,323] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'test_slack', 'slack', '2020-12-28T07:24:51.014007+00:00', '--job-id', '55', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/slag_practice.py', '--cfg-path', '/tmp/tmpl_0c0jms']
[2020-12-28 15:24:52,324] {standard_task_runner.py:76} INFO - Job 55: Subtask slack
[2020-12-28 15:24:52,368] {logging_mixin.py:103} INFO - Running <TaskInstance: test_slack.slack 2020-12-28T07:24:51.014007+00:00 [running]> on host dataiku
[2020-12-28 15:24:52,406] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=test_slack
AIRFLOW_CTX_TASK_ID=slack
AIRFLOW_CTX_EXECUTION_DATE=2020-12-28T07:24:51.014007+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-28T07:24:51.014007+00:00
[2020-12-28 15:24:52,458] {base.py:74} INFO - Using connection to: id: slack. Host: https://hooks.slack.com/services/, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:24:52,459] {http.py:140} INFO - Sending 'POST' to url: https://hooks.slack.com/services/aT01D1RB1EMQ/B01JAGMQ6TS/etZ0jlEcAO6LyyRIBSlrAn4F
[2020-12-28 15:24:52,945] {http.py:154} ERROR - HTTP error: Not Found
[2020-12-28 15:24:52,945] {http.py:155} ERROR - no_team
[2020-12-28 15:24:52,952] {taskinstance.py:1396} ERROR - 404:Not Found
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 152, in check_response
    response.raise_for_status()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hooks.slack.com/services/aT01D1RB1EMQ/B01JAGMQ6TS/etZ0jlEcAO6LyyRIBSlrAn4F

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 120, in execute
    self.hook.execute()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 166, in execute
    extra_options={'proxies': proxies, 'check_response': True},
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 141, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 191, in run_and_check
    self.check_response(response)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 156, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 404:Not Found
[2020-12-28 15:24:52,953] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=test_slack, task_id=slack, execution_date=20201228T072451, start_date=20201228T072452, end_date=20201228T072452
[2020-12-28 15:24:52,962] {base.py:74} INFO - Using connection to: id: slack. Host: https://hooks.slack.com/services/, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:24:52,962] {http.py:140} INFO - Sending 'POST' to url: https://hooks.slack.com/services/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
[2020-12-28 15:24:53,497] {local_task_job.py:118} INFO - Task exited with return code 1
