[2020-12-25 15:02:43,853] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T07:02:41.195531+00:00 [queued]>
[2020-12-25 15:02:43,855] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T07:02:41.195531+00:00 [queued]>
[2020-12-25 15:02:43,856] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 15:02:43,856] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 15:02:43,856] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 15:02:43,864] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-25T07:02:41.195531+00:00
[2020-12-25 15:02:43,866] {standard_task_runner.py:51} INFO - Started process 8200 to run task
[2020-12-25 15:02:43,868] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-25T07:02:41.195531+00:00', '--job-id', '49', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmp19e5r3s3']
[2020-12-25 15:02:43,868] {standard_task_runner.py:76} INFO - Job 49: Subtask t1
[2020-12-25 15:02:43,884] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-25T07:02:41.195531+00:00 [running]> on host dataiku
[2020-12-25 15:02:43,889] {taskinstance.py:1396} ERROR - unexpected char '$' at 65
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1224, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1684, in render_templates
    self.task.render_template_fields(context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 857, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 870, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 907, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ub/airflow/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '$' at 65
[2020-12-25 15:02:43,890] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=t1, execution_date=20201225T070241, start_date=20201225T070243, end_date=20201225T070243
[2020-12-25 15:02:43,919] {local_task_job.py:118} INFO - Task exited with return code 1
