[2020-12-28 15:09:37,453] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: test_slack.notify_slack_channel 2020-12-28T07:09:36.854961+00:00 [queued]>
[2020-12-28 15:09:37,465] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: test_slack.notify_slack_channel 2020-12-28T07:09:36.854961+00:00 [queued]>
[2020-12-28 15:09:37,466] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 15:09:37,466] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 15:09:37,466] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 15:09:37,473] {taskinstance.py:1038} INFO - Executing <Task(SlackWebhookOperator): notify_slack_channel> on 2020-12-28T07:09:36.854961+00:00
[2020-12-28 15:09:37,476] {standard_task_runner.py:51} INFO - Started process 7378 to run task
[2020-12-28 15:09:37,478] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'test_slack', 'notify_slack_channel', '2020-12-28T07:09:36.854961+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/slag_practice.py', '--cfg-path', '/tmp/tmp027n4jqn']
[2020-12-28 15:09:37,479] {standard_task_runner.py:76} INFO - Job 45: Subtask notify_slack_channel
[2020-12-28 15:09:37,522] {logging_mixin.py:103} INFO - Running <TaskInstance: test_slack.notify_slack_channel 2020-12-28T07:09:36.854961+00:00 [running]> on host dataiku
[2020-12-28 15:09:37,561] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=test_slack
AIRFLOW_CTX_TASK_ID=notify_slack_channel
AIRFLOW_CTX_EXECUTION_DATE=2020-12-28T07:09:36.854961+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-28T07:09:36.854961+00:00
[2020-12-28 15:09:37,612] {base.py:74} INFO - Using connection to: id: slack_test. Host: https://hooks.slack.com/services/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, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:09:37,620] {base.py:74} INFO - Using connection to: id: slack_test. Host: https://hooks.slack.com/services/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, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:09:37,621] {http.py:140} INFO - Sending 'POST' to url: https://hooks.slack.com/services/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
[2020-12-28 15:09:38,111] {http.py:154} ERROR - HTTP error: Forbidden
[2020-12-28 15:09:38,111] {http.py:155} ERROR - invalid_token
[2020-12-28 15:09:38,120] {taskinstance.py:1396} ERROR - 403:Forbidden
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 152, in check_response
    response.raise_for_status()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://hooks.slack.com/services/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

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 120, in execute
    self.hook.execute()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 166, in execute
    extra_options={'proxies': proxies, 'check_response': True},
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 141, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 191, in run_and_check
    self.check_response(response)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 156, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2020-12-28 15:09:38,121] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=test_slack, task_id=notify_slack_channel, execution_date=20201228T070936, start_date=20201228T070937, end_date=20201228T070938
[2020-12-28 15:09:38,128] {base.py:74} INFO - Using connection to: id: slack_test. Host: https://hooks.slack.com/services/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, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:09:38,138] {base.py:74} INFO - Using connection to: id: slack_test. Host: https://hooks.slack.com/services/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, Port: None, Schema: , Login: , Password: None, extra: None
[2020-12-28 15:09:38,139] {http.py:140} INFO - Sending 'POST' to url: https://hooks.slack.com/services/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
[2020-12-28 15:09:38,649] {http.py:154} ERROR - HTTP error: Forbidden
[2020-12-28 15:09:38,649] {http.py:155} ERROR - invalid_token
[2020-12-28 15:09:38,649] {taskinstance.py:1454} ERROR - Failed at executing callback
[2020-12-28 15:09:38,649] {taskinstance.py:1455} ERROR - 403:Forbidden
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 152, in check_response
    response.raise_for_status()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://hooks.slack.com/services/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

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 120, in execute
    self.hook.execute()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 166, in execute
    extra_options={'proxies': proxies, 'check_response': True},
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 141, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 191, in run_and_check
    self.check_response(response)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 156, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 152, in check_response
    response.raise_for_status()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://hooks.slack.com/services/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

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1452, in handle_failure
    callback(context)
  File "/home/ub/airflow/dags/slag_practice.py", line 29, in alert_slack_channel
    ).execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 120, in execute
    self.hook.execute()
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 166, in execute
    extra_options={'proxies': proxies, 'check_response': True},
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 141, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 191, in run_and_check
    self.check_response(response)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 156, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2020-12-28 15:09:38,691] {local_task_job.py:118} INFO - Task exited with return code 1
